Configure Gitpod for one-click quickstart
remix-run/indie-stack pull request #58
Opened 2022-04-09 22:02 UTC by jacobPARIS

2022-04-12 16:14 UTC, kentcdodds requested changes
Looks good. Just a couple things.

2022-04-12 16:14 UTC, kentcdodds commented on .gitpod.yml
> +    - csstools.postcss
I'd prefer to only include the plugins that are absolutely necessary:

```suggestion
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
```

2022-04-12 16:14 UTC, kentcdodds commented on README.md
> +
```suggestion
```

2022-04-14 12:48 UTC, jacobPARIS commented
> I'd prefer to only include the plugins that are absolutely necessary

Agreed, and I've adjusted the list to your recommendation. I've got a good batch of extensions I like working with, and I figured it was easier to remove the ones we don't want than to come up with the ones we do

From @andrewbrey's comment https://github.com/remix-run/remix/pull/2711
> @jacobPARIS I just gave this a try against your repository branch, and noted the prisma dev migration is not done automatically at container init. That might be a nice thing to add to the setup script (like you're doing when you create the `.env` file for the user). If you did that, clicking "open in gitpod" would launch into a fully working and initialized dev environment, db and all 👍

This was a great suggestion, and that's been implemented now too. A new user can spin up a workspace and immediately create an account with no Prisma errors

2022-04-15 22:01 UTC, kentcdodds approved these changes
Coolio 👍 Thanks for putting this together!

2022-04-15 22:01 UTC, merged

2022-04-19 09:16 UTC, MichaelDeBoey commented
@jacobPARIS Would be lovely to have these in [`blues-stack`](https://github.com/remix-run/blues-stack) & [`grunge-stack`](https://github.com/remix-run/grunge-stack) as well

2022-04-20 08:54 UTC, jacobPARIS commented
> @jacobPARIS Would be lovely to have these in [`blues-stack`](https://github.com/remix-run/blues-stack) & [`grunge-stack`](https://github.com/remix-run/grunge-stack) as well

I will make that happen :)