fix: open redirects
remix-run/indie-stack pull request #68
Opened 2022-04-19 18:21 UTC by jacob-ebey

2022-04-19 18:49 UTC, MichaelDeBoey requested changes

2022-04-19 18:49 UTC, MichaelDeBoey commented on app/routes/join.tsx
> +    redirectTo,
Maybe inline the call, so we're first doing redirects before "calculating" it?

```suggestion
    redirectTo: safeRedirect(formData.get("redirectTo"), "/"),
```

2022-04-19 18:49 UTC, MichaelDeBoey commented on app/routes/join.tsx
> +  const redirectTo = safeRedirect(formData.get("redirectTo"), "/");
```suggestion
```

2022-04-19 18:49 UTC, MichaelDeBoey commented on app/routes/login.tsx
> +    redirectTo,
Maybe inline the call, so we're first doing redirects before "calculating" it?

```suggestion
    redirectTo: safeRedirect(formData.get("redirectTo"), "/notes"),
```

2022-04-19 18:49 UTC, MichaelDeBoey commented on app/routes/login.tsx
> +  const redirectTo = safeRedirect(formData.get("redirectTo"), "/notes");
```suggestion
```

2022-04-20 15:19 UTC, kentcdodds approved these changes
I'm happy with how this is implemented 👍 Thanks!

2022-04-20 15:22 UTC, merged